#theme: jekyll-theme-midnight
remote_theme: "mmistakes/minimal-mistakes@4.20.1"
title: Fabiano's Portfolio
description: This is my personal portfolio
# show_downloads: true
google_analytics: "UA-122678291-2"

